// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortLink.Database;

#nullable disable

namespace ShortLink.Database.Migrations
{
    [DbContext(typeof(MainDb))]
    partial class MainDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ShortLink.Database.Entities.Link", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("KillTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UrlLong")
                        .HasColumnType("varchar(3000)");

                    b.Property<string>("UrlShort")
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("UrlLong")
                        .IsUnique();

                    b.HasIndex("UrlShort")
                        .IsUnique();

                    b.ToTable("links");
                });
#pragma warning restore 612, 618
        }
    }
}
